### ISSUE TITLE
`cvec` crate name

### ISSUE THREAD

**Issue by nearest-river** [haennes/cvec#1]
I made a c library called "cvec" and want to upload it's rust bindings on `crates.io` so I'm asking you for the crate name '"cvec"

**Comment by haennes** [comment]
Sorry. Forgot about this issue...
There are two reasons why I dont think transfering the name makes sense:
1. The more I keep thinking about it the more I am in favor of reserving this crate name for a future implementation of a cpp compatible  vector (when speaking about byte representation) (std::vector) for other developers
1. I actually started developing a library with this name first (this should not sound arrogant by any means - I am not a native speaker)

**Comment by nearest-river** [comment]
I'm doing the same thing but in c which is more flexible.
then why not collab on this?
[cvec](https://github.com/river-xd/cvec.git)

**Comment by haennes** [comment]
This crate was actually just written as a dependency for [this project](https://github.com/haennes/const_units) which needs the const only functionality of cvec.
So the main objective of this crate is to provide a minimal const version of the rust [std::vec](https://doc.rust-lang.org/std/vec/struct.Vec.html).
